"""
DATA FROM EMBRAER E190 AIRCRAFT.
"""

from ICARUS.conceptual.concept_airplane import ConceptAirplane
from ICARUS.conceptual.criteria.FAR.landing_criterion import (
    far_inverse_landing_criterion_cl_max,
)

UNITS_IMPERIAL: dict[str, float] = {
    "m": 3.28084,
    "m2": 10.7639,
    "kg": 2.20462,
}


Area_m = 92.53  # m^2
span_m = 28.72  # m
MTOW_kg = 47790  # kg
MLW_kg = 40800  # kg
LANDING_DIST_m = 1323  # m
TAKEOFF_DIST_m = 2256  # m
CEILING_m = 12500  # m

ASPECT_RATIO = 9  # span_m**2 / Area_m
# CONVERT TO STUPIDITY UNITS
AREA: float = Area_m * UNITS_IMPERIAL["m2"]

## TAKEOFF
MTOW: float = MTOW_kg * UNITS_IMPERIAL["kg"]
TAKEOFF_DIST: float = TAKEOFF_DIST_m * UNITS_IMPERIAL["m"]  # FAR 25.111
OSWALD_CLIMB = 0.7

## CRUISE
CRUISE_SPEED = 460  # kts
OSWALD_CRUISE = 0.85
CRUISE_MACH = 0.75  # M
CRUISE_MAX_MACH = 0.82  # M
CRUISE_ALTITUDE_MAX = CEILING_m * UNITS_IMPERIAL["m"]

## LANDING
VAT = 131  # kts VAT is Vstall * 1.3
OSWALD_LANDING = 0.7
MLW: float = MLW_kg * UNITS_IMPERIAL["kg"]
LANDING_DIST: float = LANDING_DIST_m * UNITS_IMPERIAL["m"]
# FAR_LANDING_DIST: float = LANDING_DIST / 0.6 # FAR 25.125

## ENGINE PARAMETERS
SFC = 0.64  # lb/lbf/hr
THRUST_PER_ENGINE = 20360  # lbf
NO_OF_ENGINES = 2
THRUST = THRUST_PER_ENGINE * NO_OF_ENGINES

# WEIGHT RATIO
WEIGHT_RATIO = MLW / MTOW

RANGE = 2450 + 600  # + 400 #1550 # nmi
PAYLOAD_WEIGHT = 7500 * UNITS_IMPERIAL["kg"]

RANGE = 1500 + 400  # nmi
PAYLOAD_WEIGHT = 10800 * UNITS_IMPERIAL["kg"]

CL_MAX = 2.2

CL_MAX = far_inverse_landing_criterion_cl_max(
    V_app=VAT,
    wing_loading=MLW / AREA,
)
CD_0 = 0.02

embraer_E190: ConceptAirplane = ConceptAirplane(
    AREA=AREA,
    ASPECT_RATIO=ASPECT_RATIO,
    MTOW=MTOW,
    TAKEOFF_DIST=TAKEOFF_DIST,
    CRUISE_SPEED=CRUISE_SPEED,
    CRUISE_MACH=CRUISE_MACH,
    CRUISE_MAX_MACH=CRUISE_MAX_MACH,
    CRUISE_ALTITUDE_MAX=CRUISE_ALTITUDE_MAX,
    MAX_RANGE=RANGE,
    VAT=VAT,
    MAX_LANDING_WEIGHT=MLW,
    LANDING_DIST=LANDING_DIST,
    SFC=SFC,
    THRUST_PER_ENGINE=THRUST_PER_ENGINE,
    NO_OF_ENGINES=NO_OF_ENGINES,
    WEIGHT_RATIO=WEIGHT_RATIO,
    PAYLOAD_WEIGHT=PAYLOAD_WEIGHT,
    CL_MAX=CL_MAX,
    CD_0=CD_0,
    OSWALD_LANDING=OSWALD_LANDING,
    OSWALD_CLIMB=OSWALD_CLIMB,
    OSWALD_CRUISE=OSWALD_CRUISE,
    UNITS="Imperial",
)
